staticSites:
  - name: responsive-stock-dashboard
    buildCommand: npm install && npm run build
    publishPath: build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
